modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "extra_illumination"
version = "${version}"
displayName = "Extra Illumination "
authors = "ajh123"
description = '''
Providing extra objects that can illuminate your world using electricity.
'''
#logoFile = ""

[[dependencies.extra_illumination]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_illumination]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extra_illumination]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "extra_illumination.mixins.json"
